management:
  health:
    mail:
      enabled: false
  server:
    base-path: /actuator

mybatis:
  type-aliases-package: com.xxl.job.admin.dao
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

# 通用mapper配置 https://mapperhelper.github.io
mapper:
  mappers:
    - com.xxl.job.admin.core.mapper.MyBaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  supportMethodsArguments: false #支持通过 Mapper 接口参数来传递分页参数，默认值 false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  params: count=countSql

spring:
  datasource:
    druid:
      name: xxljob23
      url: jdbc:mysql://localhost:3309/xxl_job_2.3?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: root
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 150
      initialSize: 10
      maxWait: 60000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

mailsend:
  cfg:
    service-type: 1
    javamail:
      host: smtp.exmail.qq.com
      port: 465
      user: xxx@guzt.cn
      pass: 123456
      form: 系统信息<xxx@guzt.cn>
      ssl-enable: true

xxl:
  job:
    accessToken: ''
    i18n: zh_CN
    logretentiondays: 30
    triggerPoolFastMax: 200
    triggerPoolSlowMax: 100

id:
  snowflake:
    worker-id: ${XXLJOB_WORKER_ID:1}
    datacenter-id: ${XXLJOB_DATACENTER_ID:2}
