server:
  port: 9969
  servlet:
    context-path: /xxl-job-admin

management:
  health:
    mail:
      enabled: false
  server:
    base-path: /actuator

mailsend:
  cfg:
    service-type: 1
    javamail:
      host: smtp.exmail.qq.com
      port: 465
      user: xxx@guzt.cn
      pass: 123456
      form: 系统信息<xxx@guzt.cn>
      ssl-enable: true

xxl:
  job:
    accessToken: ''
    i18n: zh_CN
    logretentiondays: 30
    triggerPoolFastMax: 200
    triggerPoolSlowMax: 100

id:
  snowflake:
    worker-id: ${XXLJOB_WORKER_ID:1}
    datacenter-id: ${XXLJOB_DATACENTER_ID:2}

mybatis:
  type-aliases-package: com.xxl.job.admin.dao
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

spring:
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  profiles:
    active: sqlserver