/*
 Navicat Premium Data Transfer
 Source Server         : Localhost-XE-ORACLE-11G
 Source Server Type    : Oracle
*/

-- ----------------------------
-- Table structure for XXL_JOB_GROUP
-- ----------------------------
DROP TABLE "XXL_JOB_GROUP";
CREATE TABLE "XXL_JOB_GROUP" (
                                 "ID" NUMBER(11) NOT NULL ,
                                 "APP_NAME" VARCHAR2(600) NOT NULL ,
                                 "TITLE" VARCHAR2(600) NOT NULL ,
                                 "ADDRESS_TYPE" NUMBER(4) NOT NULL ,
                                 "ADDRESS_LIST" VARCHAR2(3000) ,
                                 "UPDATE_TIME" TIMESTAMP(6)
);
COMMENT ON COLUMN "XXL_JOB_GROUP"."APP_NAME" IS '执行器AppName';
COMMENT ON COLUMN "XXL_JOB_GROUP"."TITLE" IS '执行器名称';
COMMENT ON COLUMN "XXL_JOB_GROUP"."ADDRESS_TYPE" IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN "XXL_JOB_GROUP"."ADDRESS_LIST" IS '执行器地址列表，多地址逗号分隔';

-- ----------------------------
-- Table structure for XXL_JOB_INFO
-- ----------------------------
DROP TABLE "XXL_JOB_INFO";
CREATE TABLE "XXL_JOB_INFO" (
                                "ID" NUMBER(11) NOT NULL ,
                                "JOB_GROUP" NUMBER(11) NOT NULL ,
                                "JOB_DESC" VARCHAR2(600) NOT NULL ,
                                "ADD_TIME" TIMESTAMP(6) ,
                                "UPDATE_TIME" TIMESTAMP(6) ,
                                "AUTHOR" VARCHAR2(600) ,
                                "ALARM_EMAIL" VARCHAR2(600) ,
                                "SCHEDULE_TYPE" VARCHAR2(600) NOT NULL ,
                                "SCHEDULE_CONF" VARCHAR2(600) ,
                                "MISFIRE_STRATEGY" VARCHAR2(600) NOT NULL ,
                                "EXECUTOR_ROUTE_STRATEGY" VARCHAR2(600) ,
                                "EXECUTOR_HANDLER" VARCHAR2(600) ,
                                "EXECUTOR_PARAM" VARCHAR2(600) ,
                                "EXECUTOR_BLOCK_STRATEGY" VARCHAR2(600) ,
                                "EXECUTOR_TIMEOUT" NUMBER(11) NOT NULL ,
                                "EXECUTOR_FAIL_RETRY_COUNT" NUMBER(11) NOT NULL ,
                                "GLUE_TYPE" VARCHAR2(600) NOT NULL ,
                                "GLUE_SOURCE" VARCHAR2(3000),
                                "GLUE_REMARK" VARCHAR2(600) ,
                                "GLUE_UPDATETIME" TIMESTAMP(6) ,
                                "CHILD_JOBID" VARCHAR2(600) ,
                                "TRIGGER_STATUS" NUMBER(4) NOT NULL ,
                                "TRIGGER_LAST_TIME" NUMBER(20) NOT NULL ,
                                "TRIGGER_NEXT_TIME" NUMBER(20) NOT NULL
);
COMMENT ON COLUMN "XXL_JOB_INFO"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL_JOB_INFO"."AUTHOR" IS '作者';
COMMENT ON COLUMN "XXL_JOB_INFO"."ALARM_EMAIL" IS '报警邮件';
COMMENT ON COLUMN "XXL_JOB_INFO"."SCHEDULE_TYPE" IS '调度类型';
COMMENT ON COLUMN "XXL_JOB_INFO"."SCHEDULE_CONF" IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN "XXL_JOB_INFO"."MISFIRE_STRATEGY" IS '调度过期策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_ROUTE_STRATEGY" IS '执行器路由策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_BLOCK_STRATEGY" IS '阻塞处理策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_TIMEOUT" IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_REMARK" IS 'GLUE备注';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_UPDATETIME" IS 'GLUE更新时间';
COMMENT ON COLUMN "XXL_JOB_INFO"."CHILD_JOBID" IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_STATUS" IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_LAST_TIME" IS '上次调度时间';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_NEXT_TIME" IS '下次调度时间';

-- ----------------------------
-- Table structure for XXL_JOB_LOCK
-- ----------------------------
DROP TABLE "XXL_JOB_LOCK";
CREATE TABLE "XXL_JOB_LOCK" (
    "LOCK_NAME" VARCHAR2(100) NOT NULL
);
COMMENT ON COLUMN "XXL_JOB_LOCK"."LOCK_NAME" IS '锁名称';

-- ----------------------------
-- Table structure for XXL_JOB_LOG
-- ----------------------------
DROP TABLE "XXL_JOB_LOG";
CREATE TABLE "XXL_JOB_LOG" (
                               "ID"                        NUMBER(20) NOT NULL,
                               "JOB_GROUP"                 NUMBER(11) NOT NULL,
                               "JOB_ID"                    NUMBER(11) NOT NULL,
                               "EXECUTOR_ADDRESS"          VARCHAR2(600),
                               "EXECUTOR_HANDLER"          VARCHAR2(600),
                               "EXECUTOR_PARAM"            VARCHAR2(1000),
                               "EXECUTOR_SHARDING_PARAM"   VARCHAR2(600),
                               "EXECUTOR_FAIL_RETRY_COUNT" NUMBER(11) NOT NULL,
                               "TRIGGER_TIME"              TIMESTAMP(6),
                               "TRIGGER_CODE"              NUMBER(11) NOT NULL,
                               "TRIGGER_MSG"               VARCHAR2(3000),
                               "HANDLE_TIME"               TIMESTAMP(6),
                               "HANDLE_CODE"               NUMBER(11) NOT NULL,
                               "HANDLE_MSG"                VARCHAR2(3000),
                               "ALARM_STATUS"              NUMBER(4) NOT NULL
);
COMMENT ON COLUMN "XXL_JOB_LOG"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL_JOB_LOG"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_ADDRESS" IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_SHARDING_PARAM" IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_TIME" IS '调度-时间';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_CODE" IS '调度-结果';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_MSG" IS '调度-日志';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_TIME" IS '执行-时间';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_CODE" IS '执行-状态';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_MSG" IS '执行-日志';
COMMENT ON COLUMN "XXL_JOB_LOG"."ALARM_STATUS" IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

-- ----------------------------
-- Table structure for XXL_JOB_LOG_REPORT
-- ----------------------------
DROP TABLE "XXL_JOB_LOG_REPORT";
CREATE TABLE "XXL_JOB_LOG_REPORT" (
                                      "ID" NUMBER(20) NOT NULL ,
                                      "TRIGGER_DAY" TIMESTAMP(6) ,
                                      "RUNNING_COUNT" NUMBER(11) NOT NULL ,
                                      "SUC_COUNT" NUMBER(11) NOT NULL ,
                                      "FAIL_COUNT" NUMBER(11) NOT NULL ,
                                      "UPDATE_TIME" TIMESTAMP(6)
);
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."TRIGGER_DAY" IS '调度-时间';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."RUNNING_COUNT" IS '运行中-日志数量';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."SUC_COUNT" IS '执行成功-日志数量';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."FAIL_COUNT" IS '执行失败-日志数量';

-- ----------------------------
-- Table structure for XXL_JOB_LOGGLUE
-- ----------------------------
DROP TABLE "XXL_JOB_LOGGLUE";
CREATE TABLE "XXL_JOB_LOGGLUE" (
                                   "ID" NUMBER(20) NOT NULL ,
                                   "JOB_ID" NUMBER(11) NOT NULL ,
                                   "GLUE_TYPE" VARCHAR2(600) ,
                                   "GLUE_SOURCE" VARCHAR2(3000),
                                   "GLUE_REMARK" VARCHAR2(600) NOT NULL ,
                                   "ADD_TIME" TIMESTAMP(6) ,
                                   "UPDATE_TIME" TIMESTAMP(6)
);
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_REMARK" IS 'GLUE备注';

-- ----------------------------
-- Table structure for XXL_JOB_REGISTRY
-- ----------------------------
DROP TABLE "XXL_JOB_REGISTRY";
CREATE TABLE "XXL_JOB_REGISTRY" (
                                    "ID" NUMBER(20) NOT NULL ,
                                    "REGISTRY_GROUP" VARCHAR2(600) NOT NULL ,
                                    "REGISTRY_KEY" VARCHAR2(600) NOT NULL ,
                                    "REGISTRY_VALUE" VARCHAR2(600) NOT NULL ,
                                    "UPDATE_TIME" TIMESTAMP(6)
);

-- ----------------------------
-- Table structure for XXL_JOB_USER
-- ----------------------------
DROP TABLE "XXL_JOB_USER";
CREATE TABLE "XXL_JOB_USER" (
                                "ID" NUMBER(20) NOT NULL ,
                                "USERNAME" VARCHAR2(600) NOT NULL ,
                                "PASSWORD" VARCHAR2(600) NOT NULL ,
                                "ROLE" NUMBER(4) NOT NULL ,
                                "PERMISSION" VARCHAR2(600)
);
COMMENT ON COLUMN "XXL_JOB_USER"."USERNAME" IS '账号';
COMMENT ON COLUMN "XXL_JOB_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "XXL_JOB_USER"."ROLE" IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN "XXL_JOB_USER"."PERMISSION" IS '权限：执行器ID列表，多个逗号分割';

-- ----------------------------
-- Primary Key structure for table XXL_JOB_GROUP
-- ----------------------------
ALTER TABLE "XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C007389" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_GROUP
-- ----------------------------
ALTER TABLE "XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C007351" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C007352" CHECK ("APP_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C007353" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C007354" CHECK ("ADDRESS_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_INFO
-- ----------------------------
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007390" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_INFO
-- ----------------------------
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007355" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007356" CHECK ("JOB_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007357" CHECK ("JOB_DESC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007358" CHECK ("SCHEDULE_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007359" CHECK ("MISFIRE_STRATEGY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007360" CHECK ("EXECUTOR_TIMEOUT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007361" CHECK ("EXECUTOR_FAIL_RETRY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007362" CHECK ("GLUE_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007363" CHECK ("TRIGGER_STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007364" CHECK ("TRIGGER_LAST_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C007365" CHECK ("TRIGGER_NEXT_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOCK
-- ----------------------------
ALTER TABLE "XXL_JOB_LOCK" ADD CONSTRAINT "SYS_C007391" PRIMARY KEY ("LOCK_NAME");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOCK
-- ----------------------------
ALTER TABLE "XXL_JOB_LOCK" ADD CONSTRAINT "SYS_C007366" CHECK ("LOCK_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOG
-- ----------------------------
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C007392" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOG
-- ----------------------------
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C007367" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C007368" CHECK ("JOB_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C007369" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C007370" CHECK ("EXECUTOR_FAIL_RETRY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C007371" CHECK ("TRIGGER_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C007372" CHECK ("HANDLE_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C007373" CHECK ("ALARM_STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_LOG
-- ----------------------------
CREATE INDEX "I_HANDLE_CODE"
  ON "XXL_JOB_LOG" ("HANDLE_CODE" ASC);
CREATE INDEX "I_TRIGGER_TIME"
  ON "XXL_JOB_LOG" ("TRIGGER_TIME" ASC);

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOG_REPORT
-- ----------------------------
ALTER TABLE "XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C007393" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOG_REPORT
-- ----------------------------
ALTER TABLE "XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C007374" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C007375" CHECK ("RUNNING_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C007376" CHECK ("SUC_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C007377" CHECK ("FAIL_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_LOG_REPORT
-- ----------------------------
CREATE UNIQUE INDEX "I_TRIGGER_DAY"
  ON "XXL_JOB_LOG_REPORT" ("TRIGGER_DAY" ASC);

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOGGLUE
-- ----------------------------
ALTER TABLE "XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C007394" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOGGLUE
-- ----------------------------
ALTER TABLE "XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C007378" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C007379" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C007380" CHECK ("GLUE_REMARK" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_REGISTRY
-- ----------------------------
ALTER TABLE "XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C007395" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_REGISTRY
-- ----------------------------
ALTER TABLE "XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C007381" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C007382" CHECK ("REGISTRY_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C007383" CHECK ("REGISTRY_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C007384" CHECK ("REGISTRY_VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_REGISTRY
-- ----------------------------
CREATE INDEX "I_G_K_V"
  ON "XXL_JOB_REGISTRY" ("REGISTRY_GROUP" ASC, "REGISTRY_VALUE" ASC, "REGISTRY_KEY" ASC);

-- ----------------------------
-- Primary Key structure for table XXL_JOB_USER
-- ----------------------------
ALTER TABLE "XXL_JOB_USER" ADD CONSTRAINT "SYS_C007396" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_USER
-- ----------------------------
ALTER TABLE "XXL_JOB_USER" ADD CONSTRAINT "SYS_C007385" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_USER" ADD CONSTRAINT "SYS_C007386" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_USER" ADD CONSTRAINT "SYS_C007387" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_USER" ADD CONSTRAINT "SYS_C007388" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_USER
-- ----------------------------
CREATE UNIQUE INDEX "I_USERNAME"
  ON "XXL_JOB_USER" ("USERNAME" ASC);



INSERT INTO XXL_JOB_LOCK VALUES ('schedule_lock');

INSERT INTO XXL_JOB_USER VALUES (1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 1, NULL);
INSERT INTO XXL_JOB_USER VALUES (2, 'devtest', 'e10adc3949ba59abbe56e057f20f883e', 0, '1');
INSERT INTO XXL_JOB_USER VALUES (3, 'mytest', 'ff9830c42660c1dd1942844f8069b74a', 0, '2');

INSERT INTO XXL_JOB_GROUP VALUES (1, 'xxl-job-executor-sample', '示例执行器', 0, NULL, SYSDATE);
INSERT INTO XXL_JOB_GROUP VALUES (2, 'wms-main-api', 'WMS仓库管理系统', 0, NULL, SYSDATE);
INSERT INTO XXL_JOB_GROUP VALUES (3, 'pay-api', '支付中心', 0, NULL, SYSDATE);



INSERT INTO XXL_JOB_INFO VALUES (1, 1, '测试任务1', SYSDATE, SYSDATE, 'XXL', '', 'CRON', '0 0 0 * * ? *', 'DO_NOTHING', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', SYSDATE, '', 0, 0, 0);
INSERT INTO XXL_JOB_INFO VALUES (2, 2, '定时检查库存', SYSDATE,SYSDATE, '徐海峰', '', 'FIX_RATE', '5', 'DO_NOTHING', 'FAILOVER', 'checkStockJobHandler', '8', 'DISCARD_LATER', 0, 0, 'BEAN', '', 'GLUE代码初始化', SYSDATE, '', 0, 0, 0);
INSERT INTO XXL_JOB_INFO VALUES (3, 3, '定时检查回调', SYSDATE,SYSDATE, '刘星', '', 'CRON', '* 2 * * * ?', 'DO_NOTHING', 'FAILOVER', 'checkPayJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', SYSDATE, '', 0, 0, 0);

